module.exports = {
  TOKEN_STATES: ['loggedIn', 'loggedOut', 'anon'],
  USER_UNAUTHENTICATED: 'UNAUTHENTICATED',
  USER_AUTHENTICATED: 'AUTHENTICATED',
  USER_ADMIN: 'ADMIN',
  USER_SERVICE_ACCOUNT: 'SERVICE_ACCOUNT',
};
